default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: monny_dev

test:
  <<: *default
  database: monny_test

production:
  <<: *default
  database: monny_prod
